In [3]:
import numpy as np

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x)

y = np.arange(15)
print(y)

[1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [7]:
z = [1,2,3,4,5,6]

%timeit [i**2 for i in z]

4.81 µs ± 90.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
b = np.arange(7)
%timeit b**2

2.27 µs ± 66 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
a = np.array([1,2,3,4,5,6,])
a

array([1, 2, 3, 4, 5, 6])

In [10]:
a.ndim

1

In [13]:
a.shape

(6,)

In [14]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
print(b.ndim)

2


In [16]:
print(b.shape)

(2, 5)


In [17]:
print(len(b))

2


In [20]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
print(c.ndim)

3


In [22]:
print(c.shape)

(2, 2, 2)


In [23]:
print(len(c))

2


In [25]:
#1D - Vector
#2D - Matrix
#3D - Tensor

In [28]:
d = np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
print(len(d))

10


In [31]:
print(d.ndim)

1


In [32]:
print(d.shape)

(10,)


In [33]:
d = np.arange(2,5,1)
print(d)

[2 3 4]


In [37]:
d = np.linspace(2,5,10)
print(d)
print(d.ndim)

[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
1


In [41]:
d = np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [42]:
d = np.zeros((10,10))
print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [44]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
d = np.eye(5,5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
d = np.diag([1,2,3,4,5,6,7,8,9])
print(d)

[[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 9]]


In [52]:
np.diag(d)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
d = np.random.rand(10) #unform distribution
d

array([0.37440005, 0.9415938 , 0.14292452, 0.33302571, 0.25919718,
       0.60534369, 0.12910752, 0.9200451 , 0.54578925, 0.5505713 ])

In [55]:
d = np.random.randn(10) #Gausian distribution
d

array([-0.06441012,  0.62375907, -0.25593736,  0.69914574,  0.49085478,
        0.27287522,  0.49521206,  0.7654371 ,  1.76954611,  0.29711957])

In [56]:
b = np.array([1,2,3,4,5,6,7,8,9])
print(b.dtype)

int32


In [59]:
b = np.arange(1,10,2, dtype = 'float64')
print(b)

[1. 3. 5. 7. 9.]


In [61]:
b = np.ones(5)
b
print(b.dtype)

float64


In [64]:
c = np.array([1+6j, 2+7j])
print(c)
c.dtype

[1.+6.j 2.+7.j]


dtype('complex128')

In [66]:
d = np.array([True, False, False, True])
d
d.dtype

dtype('bool')

In [68]:
d = np.array(['Tharun', 'Mamatha', 'Mamatharun'])
d
d.dtype

dtype('<U10')

In [80]:
c = np.arange(1,10)
c[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
d = c[1:7]
d

array([2, 3, 4, 5, 6, 7])

In [85]:
np.shares_memory(c,d)

True

In [86]:
d[0] = 10
d

array([10,  3,  4,  5,  6,  7])

In [87]:
c

array([ 1, 10,  3,  4,  5,  6,  7,  8,  9])

In [88]:
e = c[1:5].copy()
e

array([10,  3,  4,  5])

In [89]:
np.shares_memory(c,e)

False

In [83]:
c[1:7:2]

array([2, 4, 6])

In [71]:
c[::-1]

array([9, 7, 5, 3, 1])

In [72]:
c[0]

1

In [73]:
c[1:]

array([3, 5, 7, 9])

In [74]:
c[1]= 10
c

array([ 1, 10,  5,  7,  9])

In [75]:
c[2:] = [1,2,3]
c

array([ 1, 10,  1,  2,  3])

In [79]:
d = np.diag([1,2,3,4,5,6,7,8,9])
d.ndim

2

In [78]:
d[8,7] = 10
d

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 10,  9]])

In [127]:
c = np.arange(20)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
mask = (c%2 == 0)
d = c[mask]
d
d[1] = 4
d
np.shares_memory(c,d)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [92]:
c[mask] = -1
c

array([-1,  1, -1,  3, -1,  5, -1,  7, -1,  9, -1, 11, -1, 13, -1, 15, -1,
       17, -1, 19])

In [93]:
c = np.arange(1,20,2)
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [94]:
c[[2,3,2,4,2,5,5,6]]

array([ 5,  7,  5,  9,  5, 11, 11, 13])

In [95]:
c[[1,2,3,4,2]] = 100
c

array([  1, 100, 100, 100, 100,  11,  13,  15,  17,  19])

In [98]:
c = np.array([1,2,3,4,5,6,7,8,9])**2
c+1

array([ 2,  5, 10, 17, 26, 37, 50, 65, 82], dtype=int32)

In [99]:
c**2

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [101]:
d = np.array([1,22,2,5,4,8,7,9,10])
c-d

array([  0, -18,   7,  11,  21,  28,  42,  55,  71])

In [102]:
c*d

array([  1,  88,  18,  80, 100, 288, 343, 576, 810])

In [104]:
c*d

array([  1,  88,  18,  80, 100, 288, 343, 576, 810])

In [106]:
c.dot(c)

15333

In [107]:
e = np.diag([1,2,3,4,5,6,7,8,9])
e

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [108]:
e*e

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 16,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 25,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 36,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 64,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 81]])

In [109]:
e.dot(e)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 16,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 25,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 36,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 64,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 81]])

In [110]:
d == e

array([[ True, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [114]:
d.shape

(9,)

In [113]:
e.shape

(9, 9)

In [115]:
e > d 

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [118]:
f = np.diag([1,2,3,4,5,6,7,8,9])

In [119]:
np.array_equal(e,d)

False

In [120]:
np.array_equal(e,f)

True

In [132]:
b = np.array([1,1,0,1,1], dtype = 'bool')
c = np.array([0,1,0,1,1], dtype = 'bool')

np.logical_or(b,c)

array([ True,  True, False,  True,  True])

In [133]:
np.logical_and(b,c)

array([False,  True, False,  True,  True])

In [165]:
e = np.array([1,23,4,56,5])
np.sin(e)

array([ 0.84147098, -0.8462204 , -0.7568025 , -0.521551  , -0.95892427])

In [136]:
np.log(e)

array([0.        , 3.13549422, 1.38629436, 4.02535169, 1.60943791])

In [137]:
np.exp(e)

array([2.71828183e+00, 9.74480345e+09, 5.45981500e+01, 2.09165950e+24,
       1.48413159e+02])

In [138]:
e = np.array([1,23,4,56,5]) #shape mismatch
d = np.array([1,23,4,56,5,7])
e+d

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [139]:
x = np.array([1,2,3,4,5,6,7,8,9])
x.sum()

45

In [148]:
y = np.array([[1,2,3], [4,5,6]])
y[1][2]

6

In [141]:
y.sum(axis = 0)

array([5, 7, 9])

In [142]:
y.sum(axis = 1)

array([ 6, 15])

In [166]:
x.min()
min(x)

1

In [168]:
y.max()

10

In [146]:
x.argmin()

0

In [147]:
y.argmax()

5

In [150]:
y = np.array([True, False, True, False])

In [151]:
np.all(y)

False

In [152]:
np.any(y)

True

In [159]:
x = np.ones((5,5))
np.any(x == 1)

True

In [161]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
m = np.array([11,12,13,14,15])

((x<=y) & (y<=m)).all()
    

True

In [162]:
x.mean()

3.0

In [163]:
np.mean(x)

3.0

In [180]:
y = np.array([[1,2,3,7],[8,9,10,11]])
np.mean(y, axis = 0)

array([4.5, 5.5, 6.5, 9. ])

In [181]:
np.median(y, axis = 1)

array([2.5, 9.5])

In [182]:
np.std(x)

1.4142135623730951

In [184]:
x.std()

1.4142135623730951

In [185]:
np.std(y, axis = 0)

array([3.5, 3.5, 3.5, 2. ])

In [186]:
np.std(y, axis = 1)

array([2.27760839, 1.11803399])

In [2]:
# data = np.loadtxt('Populations.txt')
# data
# year, x,y,z = data.T
#print(year)
#populations = data[:, 1:]
#populations.std(axis = 0)
#np.argmax(populations, axis = 0)

In [4]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([1,2,3])

a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
a = np.tile(np.arange(1,40,19), (3,1))
a

array([[ 1, 20, 39],
       [ 1, 20, 39],
       [ 1, 20, 39]])

In [10]:
a+b

array([[ 2, 22, 42],
       [ 2, 22, 42],
       [ 2, 22, 42]])

In [11]:
b = b[:, np.newaxis ]
b

array([[1],
       [2],
       [3]])

In [12]:
a+b

array([[ 2, 21, 40],
       [ 3, 22, 41],
       [ 4, 23, 42]])

In [13]:
a = np.tile(np.arange(1,40,10), (3,2))
a

array([[ 1, 11, 21, 31,  1, 11, 21, 31],
       [ 1, 11, 21, 31,  1, 11, 21, 31],
       [ 1, 11, 21, 31,  1, 11, 21, 31]])

In [14]:
a.ndim

2

In [15]:
a.shape

(3, 8)

In [19]:
b = np.array([1,2,3,4,5,6,7,8])

In [24]:
a+b

array([[[ 2, 12, 22, 32,  2, 12, 22, 32],
        [ 2, 12, 22, 32,  2, 12, 22, 32],
        [ 2, 12, 22, 32,  2, 12, 22, 32]],

       [[ 3, 13, 23, 33,  3, 13, 23, 33],
        [ 3, 13, 23, 33,  3, 13, 23, 33],
        [ 3, 13, 23, 33,  3, 13, 23, 33]],

       [[ 4, 14, 24, 34,  4, 14, 24, 34],
        [ 4, 14, 24, 34,  4, 14, 24, 34],
        [ 4, 14, 24, 34,  4, 14, 24, 34]]])

In [25]:
a = np.tile(np.array([1,2,3,4,5,6,7,8,9]), (3,1))
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [38]:
b = np.array([10,11,12,13,14,15,16,17,18])

In [44]:
b = b[:, np.newaxis]
b.shape

(1, 1, 1, 1, 9)

In [42]:
a+b

array([[[11, 13, 15, 17, 19, 21, 23, 25, 27]]])

In [45]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [49]:
b[0] = 100

In [50]:
b

array([100,   2,   3,   4,   5,   6])

In [51]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [52]:
a.T

array([[100,   4],
       [  2,   5],
       [  3,   6]])

In [53]:
b = a.ravel()

array([100,   2,   3,   4,   5,   6])

In [55]:
b = b.reshape((2,3))
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [56]:
b[0,0] = 200
b

array([[200,   2,   3],
       [  4,   5,   6]])

In [57]:
z = np.array([1,2,33,4,5,6,7,8,9])
z

array([ 1,  2, 33,  4,  5,  6,  7,  8,  9])

In [58]:
z = z[:,np.newaxis]

In [59]:
z

array([[ 1],
       [ 2],
       [33],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9]])

In [62]:
a = np.arange(1,41,2).reshape(1,10,2)
a

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19],
        [21, 23],
        [25, 27],
        [29, 31],
        [33, 35],
        [37, 39]]])

In [63]:
a[0][7][1]

31

In [76]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
a.resize(3,3)

In [82]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [1]:
a = np.array([1,2,3,4,1,2,3,4,5])

b = np.sort(a, axis = 0)

b

NameError: name 'np' is not defined

In [2]:
b = np.argsort(a,axis = 0)

NameError: name 'np' is not defined

In [3]:
a[b]

NameError: name 'a' is not defined

In [4]:
import math

def f(x):
    return math.cos(x) - math.sin(x)
    
x_l = 0
x_u = 1
x = (x_l + x_u) / 2

while( abs(f(x)) > 0.0001):
    
    x = (x_l + x_u) / 2
    
    if f(x) > 0:
        x_l = x
    else:
        x_u = x
    
print(str(x), str(f(x)))

0.785400390625 -3.1497754101605935e-06


In [7]:
import math

def f(x):

    if x != 0:

         return abs(math.sin(x) / x)

    else :

        return math.nan

 

x = -10

x_u = 10

n = 100

 

delt = (x_u - x) / n

r = 0

 

while (x <= 10):

    if x == 0:

        continue

    r = r + f(x)*delt + (0.5)*delt*(f(x+delt) - f(x))

    x += delt

   

print(r)   

5.131854166603367


In [8]:
import math

def f(x):

       return 1
 

x = -10

x_u = 10

n = 100

 

delt = (x_u - x) / n

r = 0

 

while (x <= 10):

    if x == 0:

        continue

    r = r + f(x)*delt + (0.5)*delt*(f(x+delt) - f(x))

    x += delt

   

print(r)   

20.19999999999996
