In [19]:
import numpy as np

In [37]:
a = np.random.rand(4,5)
a

array([[0.73633459, 0.61909299, 0.47598215, 0.22101605, 0.91462153],
       [0.07116591, 0.15032181, 0.84515526, 0.12830022, 0.36465178],
       [0.01413358, 0.47931727, 0.16894697, 0.79508283, 0.42380329],
       [0.33307951, 0.16954464, 0.0169576 , 0.76854842, 0.17788729]])

In [38]:
b = np.random.rand(4,5)
b

array([[0.34719214, 0.33107493, 0.24309805, 0.96403209, 0.91431046],
       [0.65090961, 0.5246462 , 0.82168914, 0.43854225, 0.52283473],
       [0.65410211, 0.09824374, 0.0221986 , 0.63718024, 0.51507678],
       [0.56579045, 0.62370486, 0.84442827, 0.53848483, 0.53535018]])

In [47]:
a+b

array([[1.08352673, 0.95016791, 0.7190802 , 1.18504815, 1.82893199],
       [0.72207552, 0.67496801, 1.6668444 , 0.56684247, 0.8874865 ],
       [0.6682357 , 0.57756102, 0.19114557, 1.43226307, 0.93888006],
       [0.89886996, 0.7932495 , 0.86138587, 1.30703325, 0.71323747]])

In [58]:
c = np.zeros((4,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
x,y = a.shape

print(x,y)

4 5


In [60]:
for i in range(x):
    for j in range(y):
        c[i,j] = a[i,j] + b[i,j]

In [61]:
print(c)

[[1.08352673 0.95016791 0.7190802  1.18504815 1.82893199]
 [0.72207552 0.67496801 1.6668444  0.56684247 0.8874865 ]
 [0.6682357  0.57756102 0.19114557 1.43226307 0.93888006]
 [0.89886996 0.7932495  0.86138587 1.30703325 0.71323747]]


In [24]:
x = np.random.rand(2,4,5)
y = np.random.rand(2,4,5)
z = np.zeros((2,4,5))
g = x+y

print(g)

c1,c2,c3 = x.shape

for i in range(c1):
    for j in range(c2):
        for k in range(c3):
            z[i,j,k] = x[i,j,k] + y[i,j,k]
print(z)

[[[1.41528442 1.2543356  0.78710553 1.23034615 1.10580049]
  [0.80075086 0.57051413 0.2345469  0.68940601 0.99533973]
  [1.59333497 1.89756218 1.24090316 1.19688628 0.94215777]
  [0.8423843  1.2166237  1.204629   0.78972037 0.99809085]]

 [[0.68801513 1.33066634 0.57160575 1.81346688 0.54735836]
  [0.68559066 0.67798214 1.15092642 1.13215723 0.52971437]
  [1.65830407 0.59494756 0.50927852 1.49809915 1.07850388]
  [1.48877631 0.62719841 0.35114247 0.98947414 1.31857992]]]
[[[1.41528442 1.2543356  0.78710553 1.23034615 1.10580049]
  [0.80075086 0.57051413 0.2345469  0.68940601 0.99533973]
  [1.59333497 1.89756218 1.24090316 1.19688628 0.94215777]
  [0.8423843  1.2166237  1.204629   0.78972037 0.99809085]]

 [[0.68801513 1.33066634 0.57160575 1.81346688 0.54735836]
  [0.68559066 0.67798214 1.15092642 1.13215723 0.52971437]
  [1.65830407 0.59494756 0.50927852 1.49809915 1.07850388]
  [1.48877631 0.62719841 0.35114247 0.98947414 1.31857992]]]


In [6]:
c1,c2,r1 = input('Enter the circle inputs:').split()

Enter the circle inputs:1 2 1


In [7]:
x1,y1 = input('Enter the point coordinates').split()

Enter the point coordinates2 5


In [8]:
import math

In [11]:
c1 = int(c1)
c2 = int(c2)
r1 = int(r1)
x1 = int(x1)
y1 = int(y1)

In [14]:
d = math.sqrt( (c1-x1)**2 + (c2-y1)**2 )
d

3.1622776601683795

In [17]:
if d < r1:
    print('The point is insdie of the circle')
elif d == r1:
    print('The point is on the circle')
else:
    print('The point is outside of the circle')

The point is outside of the circle


In [28]:
x1,y1,x2,y2,x3,y3 = input('Enter the values of the rectangle: ').split()

Enter the values of the rectangle: 2 1 6 5 4 4


In [29]:
x1 = int(x1)
y1 = int(y1)
x2 = int(x2)
y2 = int(y2)
x3 = int(x3)
y3 = int(y3)

if x3>x1 and x2>x3 and y3 > y1 and y2 > y1:
    print('The point is inside of the rectnagle.')
else:
    print('The point is not inside of the rectangle')

The point is inside of the rectnagle.


In [37]:
c = np.random.rand(4,5)
print(c)

print(np.reshape(c, 20, 'c'))

[[0.74001788 0.49549345 0.41995663 0.1017155  0.74692987]
 [0.55489959 0.49515922 0.90484814 0.32229004 0.08211454]
 [0.21694562 0.76450144 0.17121807 0.53437631 0.82378523]
 [0.05545843 0.64929749 0.61583946 0.44697959 0.53759628]]
[0.74001788 0.49549345 0.41995663 0.1017155  0.74692987 0.55489959
 0.49515922 0.90484814 0.32229004 0.08211454 0.21694562 0.76450144
 0.17121807 0.53437631 0.82378523 0.05545843 0.64929749 0.61583946
 0.44697959 0.53759628]


In [38]:
print(np.reshape(c, 20, 'F'))

[0.74001788 0.55489959 0.21694562 0.05545843 0.49549345 0.49515922
 0.76450144 0.64929749 0.41995663 0.90484814 0.17121807 0.61583946
 0.1017155  0.32229004 0.53437631 0.44697959 0.74692987 0.08211454
 0.82378523 0.53759628]


In [39]:
print(np.reshape(c, (4,-1), 'F'))

[[0.74001788 0.49549345 0.41995663 0.1017155  0.74692987]
 [0.55489959 0.49515922 0.90484814 0.32229004 0.08211454]
 [0.21694562 0.76450144 0.17121807 0.53437631 0.82378523]
 [0.05545843 0.64929749 0.61583946 0.44697959 0.53759628]]


In [42]:
print(np.reshape(c, (5,-1), 'F'))

[[0.74001788 0.49515922 0.17121807 0.44697959]
 [0.55489959 0.76450144 0.61583946 0.74692987]
 [0.21694562 0.64929749 0.1017155  0.08211454]
 [0.05545843 0.41995663 0.32229004 0.82378523]
 [0.49549345 0.90484814 0.53437631 0.53759628]]


In [43]:
b = np.random.rand(4,5,6)
b

array([[[0.07338369, 0.80444148, 0.44715104, 0.69247755, 0.57631452,
         0.11972303],
        [0.17192763, 0.10789626, 0.10339267, 0.84490753, 0.44242854,
         0.81042573],
        [0.27311488, 0.15510454, 0.66415651, 0.05641216, 0.68487233,
         0.70869049],
        [0.31200913, 0.79093259, 0.01370957, 0.08821498, 0.1382256 ,
         0.28312869],
        [0.70863518, 0.70918111, 0.3771713 , 0.64189898, 0.04144093,
         0.18756227]],

       [[0.96058822, 0.53089367, 0.37377343, 0.64928856, 0.53804418,
         0.80295023],
        [0.68558254, 0.43405281, 0.83461682, 0.27957516, 0.60003875,
         0.46143882],
        [0.66596368, 0.826583  , 0.31389088, 0.49317713, 0.45083112,
         0.93882795],
        [0.47128937, 0.61412906, 0.98283464, 0.57575315, 0.30295977,
         0.19815838],
        [0.09914855, 0.84326655, 0.83929546, 0.7103767 , 0.35760147,
         0.6915511 ]],

       [[0.68997237, 0.96544649, 0.94079697, 0.15939098, 0.38961732,
         0.290608

In [44]:
print(np.reshape(b, (10,12)))

[[0.07338369 0.80444148 0.44715104 0.69247755 0.57631452 0.11972303
  0.17192763 0.10789626 0.10339267 0.84490753 0.44242854 0.81042573]
 [0.27311488 0.15510454 0.66415651 0.05641216 0.68487233 0.70869049
  0.31200913 0.79093259 0.01370957 0.08821498 0.1382256  0.28312869]
 [0.70863518 0.70918111 0.3771713  0.64189898 0.04144093 0.18756227
  0.96058822 0.53089367 0.37377343 0.64928856 0.53804418 0.80295023]
 [0.68558254 0.43405281 0.83461682 0.27957516 0.60003875 0.46143882
  0.66596368 0.826583   0.31389088 0.49317713 0.45083112 0.93882795]
 [0.47128937 0.61412906 0.98283464 0.57575315 0.30295977 0.19815838
  0.09914855 0.84326655 0.83929546 0.7103767  0.35760147 0.6915511 ]
 [0.68997237 0.96544649 0.94079697 0.15939098 0.38961732 0.29060825
  0.76876851 0.21186362 0.12480306 0.33545788 0.64001031 0.64549908]
 [0.60198411 0.1103235  0.39166492 0.55869664 0.12900521 0.59245712
  0.05101353 0.17617006 0.30149961 0.45792367 0.48595012 0.73534042]
 [0.0166123  0.80125933 0.56947613 0.7849

In [48]:
b = np.random.rand(4,5)
b

array([[0.65518094, 0.70600544, 0.18470401, 0.92980549, 0.20576625],
       [0.34188868, 0.06464504, 0.62111942, 0.82350953, 0.95083622],
       [0.53758161, 0.78906416, 0.18493055, 0.16149659, 0.99691285],
       [0.5418716 , 0.60452872, 0.93874473, 0.06220472, 0.61458532]])

In [49]:
print(np.reshape(b,20,'c'))

[0.65518094 0.70600544 0.18470401 0.92980549 0.20576625 0.34188868
 0.06464504 0.62111942 0.82350953 0.95083622 0.53758161 0.78906416
 0.18493055 0.16149659 0.99691285 0.5418716  0.60452872 0.93874473
 0.06220472 0.61458532]


In [50]:
print(np.reshape(b,20,'f'))

[0.65518094 0.34188868 0.53758161 0.5418716  0.70600544 0.06464504
 0.78906416 0.60452872 0.18470401 0.62111942 0.18493055 0.93874473
 0.92980549 0.82350953 0.16149659 0.06220472 0.20576625 0.95083622
 0.99691285 0.61458532]


In [86]:
a = np.random.rand(5,4)
b = np.random.rand(5,4)
print(a)
print(b)

[[0.13119523 0.36444422 0.4509048  0.48516998]
 [0.92751274 0.94813773 0.98903827 0.48220518]
 [0.67458135 0.18817606 0.91370292 0.04174916]
 [0.40884744 0.09704449 0.51776826 0.11168027]
 [0.3842156  0.79400902 0.54997509 0.79874394]]
[[0.52868809 0.18055579 0.58737443 0.7955756 ]
 [0.48766388 0.12420908 0.69715014 0.56893813]
 [0.97303464 0.34817978 0.39943833 0.33321379]
 [0.90822749 0.31275698 0.82502508 0.61313388]
 [0.62019973 0.71092471 0.58687329 0.19300008]]


In [87]:
c = np.hstack((a,b))
print(c)
d = np.concatenate((a,b), axis = 1)
print(d)

[[0.13119523 0.36444422 0.4509048  0.48516998 0.52868809 0.18055579
  0.58737443 0.7955756 ]
 [0.92751274 0.94813773 0.98903827 0.48220518 0.48766388 0.12420908
  0.69715014 0.56893813]
 [0.67458135 0.18817606 0.91370292 0.04174916 0.97303464 0.34817978
  0.39943833 0.33321379]
 [0.40884744 0.09704449 0.51776826 0.11168027 0.90822749 0.31275698
  0.82502508 0.61313388]
 [0.3842156  0.79400902 0.54997509 0.79874394 0.62019973 0.71092471
  0.58687329 0.19300008]]
[[0.13119523 0.36444422 0.4509048  0.48516998 0.52868809 0.18055579
  0.58737443 0.7955756 ]
 [0.92751274 0.94813773 0.98903827 0.48220518 0.48766388 0.12420908
  0.69715014 0.56893813]
 [0.67458135 0.18817606 0.91370292 0.04174916 0.97303464 0.34817978
  0.39943833 0.33321379]
 [0.40884744 0.09704449 0.51776826 0.11168027 0.90822749 0.31275698
  0.82502508 0.61313388]
 [0.3842156  0.79400902 0.54997509 0.79874394 0.62019973 0.71092471
  0.58687329 0.19300008]]


In [55]:
x = np.random.rand(4,4)
x

array([[0.86873296, 0.38178977, 0.87562099, 0.57224487],
       [0.05456577, 0.97831156, 0.49199699, 0.57323731],
       [0.12613512, 0.31184358, 0.01000952, 0.08420378],
       [0.32282318, 0.66959069, 0.41246493, 0.71137665]])

In [56]:
y = np.random.rand(2,4)
y

array([[0.0233359 , 0.46325931, 0.83469188, 0.74691298],
       [0.05685208, 0.07180159, 0.44610345, 0.22193743]])

In [57]:
v = np.vstack((x,y))
v

array([[0.86873296, 0.38178977, 0.87562099, 0.57224487],
       [0.05456577, 0.97831156, 0.49199699, 0.57323731],
       [0.12613512, 0.31184358, 0.01000952, 0.08420378],
       [0.32282318, 0.66959069, 0.41246493, 0.71137665],
       [0.0233359 , 0.46325931, 0.83469188, 0.74691298],
       [0.05685208, 0.07180159, 0.44610345, 0.22193743]])

In [64]:
m = np.random.rand(2,5,4)
m

array([[[0.77243986, 0.32858206, 0.12635168, 0.207321  ],
        [0.24760208, 0.6750041 , 0.51738592, 0.13702314],
        [0.65250941, 0.05918162, 0.19878143, 0.98805162],
        [0.85636271, 0.98904562, 0.92734035, 0.26390925],
        [0.3134783 , 0.78066952, 0.91161605, 0.03540625]],

       [[0.71502643, 0.92476326, 0.67811063, 0.65296681],
        [0.40533625, 0.597699  , 0.1726702 , 0.59315106],
        [0.17282672, 0.69920731, 0.77648827, 0.30619298],
        [0.81968733, 0.89405781, 0.03957422, 0.81119813],
        [0.43012349, 0.99260125, 0.77434462, 0.27609282]]])

In [70]:
n = np.random.rand(2,3,4) #height, width, depth
n

array([[[0.16657334, 0.85049065, 0.24689297, 0.14421439],
        [0.72114324, 0.75106102, 0.25769964, 0.15594166],
        [0.0423906 , 0.04493414, 0.02790174, 0.00105248]],

       [[0.04315865, 0.34716017, 0.36086538, 0.77708983],
        [0.66078135, 0.665832  , 0.20238107, 0.44717222],
        [0.91758135, 0.94163833, 0.26314597, 0.35830688]]])

In [71]:
k = np.hstack((m,n))
k

array([[[0.77243986, 0.32858206, 0.12635168, 0.207321  ],
        [0.24760208, 0.6750041 , 0.51738592, 0.13702314],
        [0.65250941, 0.05918162, 0.19878143, 0.98805162],
        [0.85636271, 0.98904562, 0.92734035, 0.26390925],
        [0.3134783 , 0.78066952, 0.91161605, 0.03540625],
        [0.16657334, 0.85049065, 0.24689297, 0.14421439],
        [0.72114324, 0.75106102, 0.25769964, 0.15594166],
        [0.0423906 , 0.04493414, 0.02790174, 0.00105248]],

       [[0.71502643, 0.92476326, 0.67811063, 0.65296681],
        [0.40533625, 0.597699  , 0.1726702 , 0.59315106],
        [0.17282672, 0.69920731, 0.77648827, 0.30619298],
        [0.81968733, 0.89405781, 0.03957422, 0.81119813],
        [0.43012349, 0.99260125, 0.77434462, 0.27609282],
        [0.04315865, 0.34716017, 0.36086538, 0.77708983],
        [0.66078135, 0.665832  , 0.20238107, 0.44717222],
        [0.91758135, 0.94163833, 0.26314597, 0.35830688]]])

In [72]:
n = np.random.rand(4,5,3)
n

array([[[0.54680808, 0.78141473, 0.30221736],
        [0.67537873, 0.38880356, 0.22340981],
        [0.43329531, 0.34921419, 0.16238634],
        [0.79590054, 0.06788889, 0.33222231],
        [0.62203724, 0.127765  , 0.18717627]],

       [[0.45393877, 0.65057792, 0.60150985],
        [0.78340046, 0.61390434, 0.25355832],
        [0.1303494 , 0.49188121, 0.42723464],
        [0.90317659, 0.93469576, 0.97281376],
        [0.59755785, 0.56325194, 0.11651292]],

       [[0.07980114, 0.23818355, 0.59622368],
        [0.32959103, 0.07108263, 0.82483558],
        [0.23013762, 0.58012906, 0.08380949],
        [0.74832375, 0.81738182, 0.51272666],
        [0.35298836, 0.73934837, 0.86580521]],

       [[0.07550933, 0.4436095 , 0.13146614],
        [0.05312942, 0.78100674, 0.95522683],
        [0.84588482, 0.88196641, 0.6006368 ],
        [0.51556496, 0.97496661, 0.76380132],
        [0.47191288, 0.92522263, 0.31687361]]])

In [73]:
m = np.random.rand(2,5,3)
m

array([[[0.60724956, 0.78067525, 0.15004736],
        [0.28241587, 0.46165187, 0.17455637],
        [0.22654978, 0.19822742, 0.07486764],
        [0.72309879, 0.77221003, 0.27729728],
        [0.27717875, 0.10539561, 0.61758994]],

       [[0.51906454, 0.38665168, 0.33525939],
        [0.13591277, 0.9366657 , 0.80588576],
        [0.37919165, 0.62455798, 0.30429842],
        [0.23379326, 0.91801483, 0.27784686],
        [0.46054342, 0.96683554, 0.51457807]]])

In [74]:
k = np.vstack((n,m))
k

array([[[0.54680808, 0.78141473, 0.30221736],
        [0.67537873, 0.38880356, 0.22340981],
        [0.43329531, 0.34921419, 0.16238634],
        [0.79590054, 0.06788889, 0.33222231],
        [0.62203724, 0.127765  , 0.18717627]],

       [[0.45393877, 0.65057792, 0.60150985],
        [0.78340046, 0.61390434, 0.25355832],
        [0.1303494 , 0.49188121, 0.42723464],
        [0.90317659, 0.93469576, 0.97281376],
        [0.59755785, 0.56325194, 0.11651292]],

       [[0.07980114, 0.23818355, 0.59622368],
        [0.32959103, 0.07108263, 0.82483558],
        [0.23013762, 0.58012906, 0.08380949],
        [0.74832375, 0.81738182, 0.51272666],
        [0.35298836, 0.73934837, 0.86580521]],

       [[0.07550933, 0.4436095 , 0.13146614],
        [0.05312942, 0.78100674, 0.95522683],
        [0.84588482, 0.88196641, 0.6006368 ],
        [0.51556496, 0.97496661, 0.76380132],
        [0.47191288, 0.92522263, 0.31687361]],

       [[0.60724956, 0.78067525, 0.15004736],
        [0.28241587, 0.461

In [79]:
n = np.random.rand(2,3,3)
n

array([[[0.62123966, 0.43460346, 0.61676329],
        [0.58926597, 0.24853801, 0.30674191],
        [0.02263467, 0.3829942 , 0.45374526]],

       [[0.76214864, 0.23169314, 0.67854876],
        [0.84442736, 0.10311395, 0.06770832],
        [0.24330805, 0.22697061, 0.429262  ]]])

In [82]:
m = np.random.rand(2,4,3)
m

array([[[0.20137452, 0.98776865, 0.79452137],
        [0.59559791, 0.16659057, 0.10807874],
        [0.40226993, 0.07553527, 0.03036981],
        [0.73991517, 0.41932469, 0.11360175]],

       [[0.71508647, 0.83130652, 0.69153404],
        [0.00510923, 0.9283628 , 0.93603198],
        [0.95045381, 0.38213871, 0.87752781],
        [0.56861112, 0.53778108, 0.09647239]]])

In [84]:
j = np.hstack((n,m))
print(j)
n = np.concatenate((n,m), axis = 1)
print(n)

[[[0.62123966 0.43460346 0.61676329]
  [0.58926597 0.24853801 0.30674191]
  [0.02263467 0.3829942  0.45374526]
  [0.20137452 0.98776865 0.79452137]
  [0.59559791 0.16659057 0.10807874]
  [0.40226993 0.07553527 0.03036981]
  [0.73991517 0.41932469 0.11360175]]

 [[0.76214864 0.23169314 0.67854876]
  [0.84442736 0.10311395 0.06770832]
  [0.24330805 0.22697061 0.429262  ]
  [0.71508647 0.83130652 0.69153404]
  [0.00510923 0.9283628  0.93603198]
  [0.95045381 0.38213871 0.87752781]
  [0.56861112 0.53778108 0.09647239]]]
[[[0.62123966 0.43460346 0.61676329]
  [0.58926597 0.24853801 0.30674191]
  [0.02263467 0.3829942  0.45374526]
  [0.20137452 0.98776865 0.79452137]
  [0.59559791 0.16659057 0.10807874]
  [0.40226993 0.07553527 0.03036981]
  [0.73991517 0.41932469 0.11360175]]

 [[0.76214864 0.23169314 0.67854876]
  [0.84442736 0.10311395 0.06770832]
  [0.24330805 0.22697061 0.429262  ]
  [0.71508647 0.83130652 0.69153404]
  [0.00510923 0.9283628  0.93603198]
  [0.95045381 0.38213871 0.87752

In [88]:
n = np.random.rand(2,3,3)
n

array([[[0.91055235, 0.36670038, 0.53725512],
        [0.55350132, 0.99006402, 0.65825566],
        [0.95617404, 0.7999772 , 0.91750523]],

       [[0.29218397, 0.72705543, 0.88133534],
        [0.73802426, 0.83673283, 0.86544011],
        [0.10006958, 0.19666491, 0.31756492]]])

In [89]:
m = np.random.rand(3,3,3)
m

array([[[0.70382991, 0.12543446, 0.33159079],
        [0.38118025, 0.46166775, 0.07078747],
        [0.38630505, 0.51960395, 0.07647004]],

       [[0.80281402, 0.09024286, 0.90621396],
        [0.00928195, 0.90634927, 0.98869312],
        [0.97374692, 0.24419356, 0.15428809]],

       [[0.24209072, 0.80452949, 0.57416109],
        [0.77083735, 0.42117534, 0.72746816],
        [0.65436264, 0.83970131, 0.75114425]]])

In [90]:
l = np.concatenate((n,m), axis = 0)
l

array([[[0.91055235, 0.36670038, 0.53725512],
        [0.55350132, 0.99006402, 0.65825566],
        [0.95617404, 0.7999772 , 0.91750523]],

       [[0.29218397, 0.72705543, 0.88133534],
        [0.73802426, 0.83673283, 0.86544011],
        [0.10006958, 0.19666491, 0.31756492]],

       [[0.70382991, 0.12543446, 0.33159079],
        [0.38118025, 0.46166775, 0.07078747],
        [0.38630505, 0.51960395, 0.07647004]],

       [[0.80281402, 0.09024286, 0.90621396],
        [0.00928195, 0.90634927, 0.98869312],
        [0.97374692, 0.24419356, 0.15428809]],

       [[0.24209072, 0.80452949, 0.57416109],
        [0.77083735, 0.42117534, 0.72746816],
        [0.65436264, 0.83970131, 0.75114425]]])

In [5]:
#finding peaks

l = [11,3,4,5,7,6,4,5,10,15]

if l[0] >= l[1]:
    print('The peak is {}'.format(l[0]))
if l[9] >= l[8]:
    print('The peak is {}'.format(l[9]))

for i in range(1, len(l)-1):
    if l[i] >= l[i+1] and l[i] > l[i-1]:
        print(l[i])

The peak is 11
The peak is 15
7


In [4]:
k = [15,2,3,1,4,5,6,9,2,1,4,17]
w = 3
max = 0
for i in range(0,len(k)-w+1):
    max = k[i]
    for j in range(1,w):
        if k[i+j] >= max:
            max = k[i+j]
    print(max)

15
3
4
5
6
9
9
9
4
17


In [2]:
from itertools import permutations
p = permutations([1,2,3,4])
for i in list(p):
    print(i)

(1, 2, 3, 4)
(1, 2, 4, 3)
(1, 3, 2, 4)
(1, 3, 4, 2)
(1, 4, 2, 3)
(1, 4, 3, 2)
(2, 1, 3, 4)
(2, 1, 4, 3)
(2, 3, 1, 4)
(2, 3, 4, 1)
(2, 4, 1, 3)
(2, 4, 3, 1)
(3, 1, 2, 4)
(3, 1, 4, 2)
(3, 2, 1, 4)
(3, 2, 4, 1)
(3, 4, 1, 2)
(3, 4, 2, 1)
(4, 1, 2, 3)
(4, 1, 3, 2)
(4, 2, 1, 3)
(4, 2, 3, 1)
(4, 3, 1, 2)
(4, 3, 2, 1)


In [33]:
def per(lst):
    
    if len(lst) == 1:
        return [lst]
    p = []
    for i in lst:
        rem = [x for x in lst if x != i]
        l = per(rem)
        
        for k in l:
            p.append([i]+k)
    return p
    
lis = [1,2,3]
p = per(lis)
print(p)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


list

In [1]:
def com(lst,n):
    
    if n == 0:
        return [[]]
    c = []
    
    for i in range(len(lst)):
        m = lst[i]
        rem = lst[i+1:]
        k = com(rem,n-1)
        
        for j in k:
            c.append([m] + j)
    return c

print(com([1,2,3],2))

[[1, 2], [1, 3], [2, 3]]


In [2]:
import sys
print(sys.version)

3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]


In [12]:
b = [1,11,2,3,4,5,6,7,23]

if b[0] >= b[1]:
    print(b[0]
if b[-1] >= b[-2]:
    print(b[-1])
for i in range(1,len(b)-1):
       if b[i] >= b[i-1] and b[i] >= b[i+1]:
             print(b[i])


SyntaxError: invalid syntax (<ipython-input-12-6f9cc5b52eed>, line 6)

In [20]:
l = [11,3,4,5,7,6,4,5,10,15]

if l[0] >= l[1]:
    print('The peak is {}'.format(l[0]))
if l[9] >= l[8]:
    print('The peak is {}'.format(l[9]))

for i in range(1, len(l)-1):
    if l[i] >= l[i+1] and l[i] >= l[i-1]:
        print(l[i])

The peak is 11
The peak is 15
7


In [3]:
import math

def f(x):
    return math.cos(x) - math.sin(x)
    
x_l = 0
x_u = 1
x = (x_l + x_u) / 2

while( abs(f(x)) > 0.0001):
    
    x = (x_l + x_u) / 2
    
    if f(x) > 0:
        x_l = x
    else:
        x_u = x
    
print(str(x), str(f(x)))

0.785400390625 -3.1497754101605935e-06


In [6]:
import math

def f(x):
    return x**5 - x**4 + 2*x**3 - x**2 + x - 3
x_l = 1
x_u = 1.5

x = (x_l + x_u) / 2

while (abs(f(x)) > 0.0000001):
    
    x = (x_l + x_u) / 2
    
    if f(x) > 0:
        x_u = x
    else:
        x_l = x

print(x, f(x))

1.1355516910552979 9.948123214087445e-09


In [11]:
import math
def f(x):
    if x != 0:
        return abs((math.sin(x)) / x)
    else:
        return math.nan
x = -10
x_u = 10

n = 100
r = 0

delt = (x_u - x)/n

while (x <= 10):
    
    if x == 0:
        continue
    
    r = r + f(x) * delt
    
    x += delt
    
print(r)
    
    
    



5.130432861167225


In [4]:
import math
def f(x):
    return 1
x = -10
x_u = 10

n = 100
r = 0

delt = (x_u - x)/n

while (x <= 10):
    
    if x == 0:
        continue
    
    r = r + f(x) * delt
    
    x += delt
    
print(r)

20.19999999999996


In [3]:
import math

def f(x):

    if x != 0:

         return abs(math.sin(x) / x)

    else :

        return math.nan

 

x = -10

x_u = -10

n = 100

 

delt = (x_u - x) / n

r = 0

 

while (x <= 10):

    if x == 0:

        continue

    r = r + f(x)*delt + (0.5)*delt*(f(x+delt) - f(x))

    x += delt

   

print(r)   

KeyboardInterrupt: 